### ISSUE TITLE
Calling sortBy doesn't work on a PipelinedRDD, causes error in Images.toSeries()

### ISSUE THREAD

**Issue by npyoung** [thunder-project/thunder#119]
Calling `tseries = Images(my_volume_stack_rdd).toSeries()` leads to the following error (only bottom of stack shown).

```python
/usr/lib/python2.7/site-packages/thunder/rdds/imageblocks.pyc in _groupIntoSeriesBlocks(self)
     87         # sort must come after group, b/c group will mess with ordering.
     88         # return self.rdd.groupByKey().sortByKey(ascending=True).mapValues(lambda v: ImageBlockValue.fromPlanarBlocks(v, 0))
---> 89         sortedRdd = self.rdd.groupByKey().sortBy(lambda (k, _): k[::-1])
     90         return sortedRdd.mapValues(lambda v: ImageBlockValue.fromPlanarBlocks(v, 0))
     91 

AttributeError: 'PipelinedRDD' object has no attribute 'sortBy'
```

PipelinedRDD subclasses RDD and should have a sortBy method, but evidently this method goes missing from whatever rdd.groupByKey returns. May be in a bug in Spark, but I haven't seen anything from anyone else with this issue.

**Comment by industrial-sloth** [comment]
What is `my_volume_stack_rdd` in this case, and how was it generated?

Also, I'm guessing this is with a previously released version (0.4.1?) and not the current master branch? (`thunder.__version__` should give you this).

There are lots of unit tests covering converting images to series, so it's unlikely that this functionality is completely broken, but you may have hit an edge case of some kind.

**Comment by industrial-sloth** [comment]
I haven't had any luck in reproducing this so far. Here's what I've been doing:
```python
from thunder.rdds.images import Images
import numpy as np
ary = np.arange(12).reshape((3,4))
init_rdd = tsc._sc.parallelize([(0,ary),(1,ary),(2,ary)])
mapped_rdd = init_rdd.mapValues(lambda v: v+1)
srs = Images(mapped_rdd).toSeries()  # no problem so far
type(mapped_rdd)  # returns PipelinedRDD
srs.count()  # returns 12
```
This is working for me with the current master code and Thunder 0.4.1, and Spark 1.2.0 and Spark 1.1.0. 

If you happen to be using a version of Spark prior to 1.1.0, I'd suggest upgrading - and we should probably be more explicit about our expectations as to Spark versions, I though we had this somewhere obvious in the documentation but a brief look isn't turning it up for me.

**Comment by npyoung** [comment]
Was running Spark 1.2.0, but using older Thunder. Upgraded Thunder to master and am now getting a different error, but it comes from netty, deep within Spark. Presumably no longer a Thunder issue. Thanks for looking into it.

**Comment by freeman-lab** [comment]
Ok great thanks for the update. Happy to try and help debug the netty issue, is this running locally, or on a cluster?

**Comment by npyoung** [comment]
This is on an EC2 cluster. I added a few more instances and upped spark.default.parallelism to 8 x N_cores (from 4x) and things seem to be working more smoothly.

**Comment by raj-sivakumar-zz** [comment]
I'm having this problem on spark 2.2.1 Any updates?
