### ISSUE TITLE
Extend exportAsPng() to use more kwag of imsave()

### ISSUE THREAD

**Issue by tomsains** [thunder-project/thunder#136]
exportAsPngs() currently does not take the same arguments as imsave()
So when saving a movie, the exportAsPngs function automatically corrects the contrast on a image by image basis creating a inconsistent movie.  

- It would be useful to be able to set both colormaps (cmap) and adjust contrast (vmin/vmax).

**Comment by freeman-lab** [comment]
Fixed by https://github.com/thunder-project/thunder/pull/137
