### ISSUE TITLE
Block padding fails in source extraction algorithms

### ISSUE THREAD

**Issue by ahwillia** [thunder-project/thunder#167]
I tweaked [this example notebook (for the neurofinder challenge)](http://nbviewer.ipython.org/github/codeneuro/neurofinder/blob/master/notebooks/creating-images-and-sources.ipynb) to include padded blocks, `padding=10`. This fails because coordinates outside the bounds of the image are returned.

    from thunder import Colorize
    image = Colorize.image
    import seaborn as sns
    sns.set_context("poster")
    data, ts, truth = tsc.makeExample('sources', centers=10, noise=1.0, returnParams=True)
    im = data.mean()
    from thunder import SourceExtraction
    model = SourceExtraction('nmf').fit(data, size=(25,25),padding=10)
    image(model.masks((100,200), base=im))

This produces the following error:

    IndexError: index 100 is out of bounds for axis 0 with size 100

**Comment by freeman-lab** [comment]
@ahwillia did you want to submit that patch we came up with in the chatroom? If not no worries, will add myself. I'm in the middle of expanding/fixing some other block/merge related features that could use this fix.

**Comment by ahwillia** [comment]
The fix you last suggested didn't quite work for me. (I think.) But it was definitely on the right track. Go ahead and add the fix -- I am out of town and unable to do so.

**Comment by freeman-lab** [comment]
Ok cool thanks, I'll track it down!
