### ISSUE TITLE
Fish data set has disappeared?

### ISSUE THREAD

**Issue by TedMorris54** [thunder-project/thunder#179]
Seems that the mouse data has over-written the zebrafish data set.

**Comment by freeman-lab** [comment]
Do you mean the toy local examples included with Thunder? As far as I can tell those both should be there, on both the most recent release (0.5.0) and on master (for example, see [here](https://github.com/thunder-project/thunder/tree/master/python/thunder/utils/data)). To load either, in two different formats (images and series), this works:

```
data = tsc.loadExample('fish-images')
data = tsc.loadExample('fish-series')
data = tsc.loadExample('mouse-images')
data = tsc.loadExample('mouse-series')
```
If any of those don't work, maybe tell us the system / version you are running and the error?

**Comment by TedMorris54** [comment]
Apologies, Jeremy - my mistake.  I think I was thrown by the comment in 
the Git repo "Adding toy example mouse data".  I shouldn't do this stuff 
at 6:30 in the morning without a pot of coffee.


Ted Morris
IBM Emerging Technologies Group | jStart® Team
Office    +1 919 486 0181
Mobile    +1 507 250 0602
Email      eamorris@us.ibm.com

**Comment by freeman-lab** [comment]
No worries @TedMorris54  coffee almost always helps =) I'll close this but let us know if you have further issues! And if it's a quick question you can also feel free to post to the [gitter](https://gitter.im/thunder-project/thunder).
