### ISSUE TITLE
Series.correlate() fails when index is multi-level

### ISSUE THREAD

**Issue by jwittenbach** [thunder-project/thunder#194]
`Series.correlate(x)` checks that the length of `x` is the same as the length of the `Series.index`. However it does this through `numpy.size(self.index)`. However, in the case that the argument to `size` is more than one-dimensional, it returns the total number of elements in the array, not the length of the first dimension, as would be correct for a multi-index.

Simple solution: `size(self.index)` should be replaced with `self.index.shape[0]`.

**Comment by freeman-lab** [comment]
Fixed on 1.0.0 branch
