### ISSUE TITLE
Image returned from loadImages has keys that are not tuples

### ISSUE THREAD

**Issue by jwittenbach** [thunder-project/thunder#199]
The keys on an `Image` object returned from `tsc.loadImages()` has keys that are integer-valued rather than tuple-valued. While these keys are one-dimensional, they should still be wrapped in a tuple for consistency.

NB: This might be a problem for a common ancestor to both `Images` and `Series` that expects such a form.

**Comment by freeman-lab** [comment]
Completely agree this is a problematic inconsistency in usage, though strictly doesn't cause any errors on its own. It definitely precludes a common ancestor that relies on keys always being a tuple, so we'll want to change this at some point soon.

**Comment by andrewgiessel** [comment]
Looking at this now.

It seems the problem actually extends to all methods in https://github.com/thunder-project/thunder/blob/master/thunder/rdds/fileio/imagesloader.py, ( `fromArrays()`, `fromStack()`, `fromOCP()`, `fromTif()`, and `fromPng()`) and thus holds for for `tsc.loadImagesFromArray()`, `tsc.loadImagesOCP()` and `tsc.loadImagesAsSeries()`, among others.

They all basically build an RDD and return the result of `Image(rdd, nrecords)`. Unless otherwise directed, my thought is to implement the tuple wrapping in each method.  This is a bit redundant but is easier to read and reason about.

**Comment by andrewgiessel** [comment]
Ok, I started working on this (here)[https://github.com/thunder-project/thunder/compare/wrap-image-keys-in-tuples] but tests started failing and I need to call it for the evening.

The map seems to work correctly and creation of image objects succeeds.  It seems like downstream methods fail, tho:  



    1) ERROR: test_load3dStackAsSeriesWithShuffle (test_context.TestContextLoading)

    Traceback (most recent call last):
     test_context.py line 57 in test_load3dStackAsSeriesWithShuffle
      rangeSeriesAry = rangeSeries.pack()
     /Users/andrewgiessel/anaconda/lib/python2.7/site-packages/thunder_python-0.6.0.dev0-py2.7.egg/thunder/rdds/series.py line 546 in pack
       result = out.rdd.values().collect()

    ...

     File "/Users/andrewgiessel/anaconda/lib/python2.7/site-packages/thunder_python-0.6.0.dev0-py2.7.egg/thunder/rdds/imgblocks/strategy.py", line 251, in blockingFunction
       yield self.extractBlockFromImage(imgAry, blockSlices, tpIdx, totNumImages)
     File "/Users/andrewgiessel/anaconda/lib/python2.7/site-packages/thunder_python-0.6.0.dev0-py2.7.egg/thunder/rdds/imgblocks/strategy.py", line 240, in extractBlockFromImage
       imgSlices = [slice(timepoint, timepoint+1, 1)] + list(blockSlices)
    TypeError: can only concatenate tuple (not "int") to tuple

I don't understand enough about the image blocks to debug this tonight, but will crack on it soon

**Comment by andrewgiessel** [comment]
I am going to close this issue.  Changing functionality at this level is better spent by a complete port of the underlying code to use Bolt instead.  Happy to re-open but as @jwittenbach said, it's more an awareness that consistency in key / value structure is important to maintain as we consider using Bolt as a backend.
