### ISSUE TITLE
Support for Python 3.4

### ISSUE THREAD

**Issue by andrewgiessel** [thunder-project/thunder#209]
Thunder should have support for Python 3.4.

**Comment by auvipy** [comment]
+python 3.5

**Comment by freeman-lab** [comment]
Thanks @auvipy , this will definitely happening as part of the major refactoring currently underway, and almost finished!

https://github.com/thunder-project/thunder/pull/237

**Comment by jwittenbach** [comment]
Added support for Python 3.4 in #247 and Python 3.5 is #270
