### ISSUE TITLE
thunder executable fails at line 40 - commenting out line seems to work

### ISSUE THREAD

**Issue by npyoung** [thunder-project/thunder#22]
/usr/bin/thunder raises an IndexException at line 40 when trying to access egg[0]. Commenting out the line seems to fix it without adverse side effects. Evidently egg is not always of len > 0.

Issue appears using thunder from the pypi repos on the Amazon EC2 AMI.

**Comment by andrewgiessel** [comment]
@npyoung Is this still a problem, or has it been fixed in recent versions?  Thanks!

**Comment by npyoung** [comment]
I haven't seen this reappear since v0.5.0.
