### ISSUE TITLE
pip install thunder-python fails

### ISSUE THREAD

**Issue by magsol** [thunder-project/thunder#257]
`No matching distribution found for distribute==0.0`

(setup: Anaconda + Python 2.7.11)

It looks like the `distribute` package [has been deprecated](http://pythonhosted.org/distribute/) and re-merged with `setuptools` fairly recently. I know you're in the middle of a major refactor and push for 1.0, so my apologies if you were already aware of this.

**Comment by freeman-lab** [comment]
@magsol thanks for having flagged this! The 1.0.0 version of `thunder-python` should now be published, mind confirming that that one installs correctly?

**Comment by magsol** [comment]
`Successfully installed bolt-python-0.5.1 thunder-python-1.0.0`

Worked perfectly! Thanks!

**Comment by freeman-lab** [comment]
terrific, thanks!
