### ISSUE TITLE
docstring inconsistency in thunder.images.images.Images.max() (python 3)

### ISSUE THREAD

**Issue by d-v-b** [thunder-project/thunder#274]
I get some weird behavior when querying the docstrings for `images.max()` in the jupyter notebook using python 3. 

```
test_im = td.images.fromrandom()
test_im.max?
```
gives me the correct docstring in the little popup thingy on the bottom of the notebook. but:

```
test_im = td.images.fromrandom()
test_im[0].max?
```

gives me what looks like the docstring for the builtin `max()` function: 

```

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method
```
This might be an issue with jupyter / ipython, because
`test_im[0].max.__doc__` returns the correct result.

**Comment by freeman-lab** [comment]
Thanks @d-v-b , I think you're right that jupyter is failing to get the right docstrings when chaining methods. If I do

```
test_im = td.images.fromrandom()
first = test_im[0]
first.max?
```
I get the right docstring info as well.

**Comment by freeman-lab** [comment]
As further evidence, the following yields the docstring for the built-in `max`, rather than the `numpy` max function:

```
import numpy as np
test = np.arange(5)
test[0].max?
```

**Comment by freeman-lab** [comment]
Closing the issue as there is nothing `thunder`-specific about this.
