### ISSUE TITLE
[py3k] indexing data[-1] returns object with invalid dimensions

### ISSUE THREAD

**Issue by d-v-b** [thunder-project/thunder#275]
Indexing with `-1` returns an object with an empty first dimension. The following code demonstrates with an `images` object, but this issue is not specific to `images`. 

```
import thunder as td
test_im = td.images.fromrandom()
print(test_im[0].shape)
print(test_im[-1].shape)
```

The code causing this issue is here: https://github.com/thunder-project/thunder/blob/master/thunder/base.py#L200

When the index =  `-1` a slice object is generated with the call `slice(-1, 0, None)`, which doesn't return a contentful slice and thus the resulting array is empty. 
`slice(-2, -1, None)` works fine, so I think this is just a special case for indexing with `-1`. `slice(-1, None, None)` makes a slice that does return the last item in an iterable, so probably the code in `base.py` needs an `if` statement checking whether the index is `-1`, unless there's a cleaner solution? If not I can get a PR together for this.

**Comment by jwittenbach** [comment]
I've been looking into this and I think there are some deeper issues involving how indexing works in Bolt that is independent of Python 2 vs 3, though we need to make sure that the results are consistent between the two versions.

**Comment by jwittenbach** [comment]
I'm currently working on cleaning up indexing across both Bolt and Thunder.

**Comment by jwittenbach** [comment]
@d-v-b this issue should be fixed now, as well as support for a lot of other indexing patterns added. Let us know if you find any other issues with this.
