### ISSUE TITLE
[py3k] PYTHONHASHSEED issue foils shuffles?

### ISSUE THREAD

**Issue by d-v-b** [thunder-project/thunder#276]
The following code in python 3.5.1 fails:
```
import thunder as td
td.images.fromrandom(engine=sc).toseries().count()
```

The punch line of the error report is this: 
```
File "/usr/local/spark-current/python/lib/pyspark.zip/pyspark/rdd.py", line 74, in portable_hash
    raise Exception("Randomness of hash of string should be disabled via PYTHONHASHSEED")
Exception: Randomness of hash of string should be disabled via PYTHONHASHSEED
```

Search for `PYTHONHASHSEED` on google suggests that this is an issue people have solved by running shell scripts on all the workers to set the `PYTHONHASHSEED`, so I will explore some of these options on our cluster

**Comment by jwittenbach** [comment]
Looks like this is a known issue with Python3 and Spark. Here is a work-around, but it's not terribly pretty: http://blog.stuart.axelbrooke.com/python-3-on-spark-return-of-the-pythonhashseed/

Could you test that out @d-v-b? If it works, it's possible that we could add to the `start-spark` script.

**Comment by d-v-b** [comment]
So this issue is (a) not thunder-specific and (b) no longer a problem on my end. I think it was derived from an incomplete migration of pyspark from python 2.7 to python 3.x. Gonna close it on those grounds.
