### ISSUE TITLE
I cannot access Colorize from thunder

### ISSUE THREAD

**Issue by ObadaM** [thunder-project/thunder#304]
Hi all, 

I am trying to run my first code example in Thunder but when it comes to "from thunder import Colorize" it gives error that Colorize is not exist. 
I installed thunder as described in the installation page. 

Any idea why I get this error.

**Comment by freeman-lab** [comment]
@ObadaM it sounds like you're looking at a tutorial based on an earlier version, that function is no longer in `thunder` as of `v1.0.0`, though some of the same functionality is now in the separate [`showit`](https://github.com/freeman-lab/showit) package.

Mind telling us what example code / tutorial you were looking at?

**Comment by ObadaM** [comment]
@freeman-lab Thanks for your fast response! 
I am trying to implement the example from this link
[](http://thunder-project.org/thunder/docs/tutorials/thunder_context.html)

But is there any tutorial for the new release because it is hard to find the new location.

**Comment by freeman-lab** [comment]
Thanks for flagging this @ObadaM ! All documentation is now at:

[docs.thunder-project.org](http://docs.thunder-project.org)

Note that there are only four tutorials, we're still in the process of rewriting the others, but those four should be correct.

And I've renamed that old doc page to `doc-legacy` to prevent others from being confused by this, and removed the erroneous tutorials.

**Comment by ObadaM** [comment]
@freeman-lab sorry for the late reply. 
Thanks a lot!!
