### ISSUE TITLE
Selecting thunder address in receive field: cpu goes to and remains at 100% until closed

### ISSUE THREAD

**Issue by sumBTC** [thunder-project/thunder#308]
(my first issue post on github so I hope I'm doing it right)

This happens on both my 32bit machine and my 64bit machine (Ubuntu 14.04)

So I click the Receive button and it opens. 
CPU (as seen with top) goes up but then low again.
If I now select the whole address field by clicking three times fast, it selects the whole address ( like: 00000000000003e8298fdcdca7ba10a185e03feed9bcb86d26896d76020ab5c6876de992ce73bc8835eb28a8186385892ccf19b44d8c1662ae0eedaccd) but the CPU on my machine goes to 100% and stays that high. Only when I close the receive field (by clicking Close)  CPU normalizes again.

On start-up I get the error messages:
libGL error: failed to authenticate magic 65
libGL error: failed to load driver: i915
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

As I wrote on Reddit, I installed by doing:
sudo apt-get install maven
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
git clone https://github.com/blockchain/thunder.git
cd thunder
./build.sh

**Comment by freeman-lab** [comment]
I think you have the wrong library, and are looking for https://github.com/blockchain/thunder

**Comment by freeman-lab** [comment]
And welcome to GitHub!

**Comment by sumBTC** [comment]
Thanks, you are of course right! First time is always a bit awkward. Thanks for the welcome and I'll go where I belong :-)
