### ISSUE TITLE
Wrong dtype with spark after conversion

### ISSUE THREAD

**Issue by boazmohar** [thunder-project/thunder#309]
I found this while trying to load from binary an `images` object that was converted from
`int16` to `float 32`.
I haven't dug deep enough to understand all the cases this could happen but here is a minimal example:

```python
import thunder as td
data = td.images.fromrandom(engine=sc)
data
out: Images
mode: spark
dtype: float64
shape: (10, 50, 50)

data = data.astype(np.float32)
data
out: Images
mode: spark
dtype: <type 'numpy.float32'>
shape: (10, 50, 50)
```
Not a problem in local mode:
```python
import thunder as td
data = td.images.fromrandom()
data
out: Images
mode: local
dtype: float64
shape: (10, 50, 50)

data = data.astype(np.float32)
data
out: Images
mode: local
dtype: float32
shape: (10, 50, 50)
```
Not obviously in bolt:
```python
from numpy import arange, repeat
from bolt import array 
x = arange(2*3*4).reshape(2, 3, 4).astype(np.float64)
b = array(x, sc, axis=0)
b.dtype
out: dtype('float64')
b.astype(np.float32)
b
out: dtype('float32')
```

**Comment by freeman-lab** [comment]
Just a quick question to better understand, is this simply an issue of how it's displayed, or is there a functional consequence?

**Comment by boazmohar** [comment]
The functional thing is the config file for binary has a dtype that is wrong.

Thanks,
Boaz On Thu, May 19, 2016 at 3:25 PM, Jeremy Freeman < notifications@github.com [notifications@github.com] > wrote:
Just a quick question to better understand, is this simply an issue of how it's displayed, or is there a functional consequence?
