### ISSUE TITLE
set _ordered = true the default for images.fromList()

### ISSUE THREAD

**Issue by d-v-b** [thunder-project/thunder#338]
When creating an `images` object using the `fromList` method, the underlying `bolt.array` object appears to have `_ordered == False`, which results in any `rdd` operation on that array requiring a `sortByKey`, which isn't so great when the `rdd` is actually ordered in the first place. The default value for `_ordered` should probably be `True` in this case.

**Comment by freeman-lab** [comment]
@d-v-b great idea! Was just discussing with @jwittenbach that this alone might be responsible for a few of the performance regressions we've been seeing.

**Comment by freeman-lab** [comment]
@jwittenbach is doing some large-scale testing now to confirm

**Comment by jwittenbach** [comment]
Closed by #339

**Comment by d-v-b** [comment]
great, thanks!
