### ISSUE TITLE
Testing with Spark 2.0

### ISSUE THREAD

**Issue by laserson** [thunder-project/thunder#359]
I couldn't tell from the README whether Thunder has been tested with Spark 2.0. A Anyone give it a shot?

**Comment by jwittenbach** [comment]
I think @boazmohar has tried this.

**Comment by boazmohar** [comment]
@laserson Yes, I am working with a nightly of Spark 2.0 and thunder is working great with it. I will be tasting the release version this week and will update here with what I find.

**Comment by freeman-lab** [comment]
@boazmohar awesome thanks for confirming, if all the tests run for you locally on Spark 2.0, maybe open a PR that installs 2.0 on travis?

**Comment by boazmohar** [comment]
Sure, I will try later today.

**Comment by freeman-lab** [comment]
Closed by https://github.com/thunder-project/thunder/pull/360
